import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist ,Space_Mono} from "next/font/google";
import BackendWaker from "~/components/backendwalker";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "700"],
});
const spaceMono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-space-mono",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} ${spaceMono.variable}`}>

      <body>
        
        <BackendWaker />
        {children}
        </body>
    </html>
  );
}
